services:
  db:
    container_name: airbnb_db
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: airbnb_clone_development
  web:
    container_name: airbnb_web
    image: ruby:3.4.4
    working_dir: /app
    command: bash -c "bundle install && rails server -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://test:test@db:5432/airbnb_clone_development

volumes:
  pgdata: